### ISSUE TITLE
Set up new Github credentials for travis CI

### ISSUE THREAD

**Issue by ryanoglesby08** [telus/browserslist-config#6]
This repository uses semantic-release and Travis CI to deploy to npm, which needs a Github personal access token in order to make the release. I've generated a token under my personal Github account.

As I will be leaving the project soon, this token will be deactivated and will need to be set up by someone else to continue using semantic-releae and Travis for deploys.

**Comment by ruxandrafed** [comment]
No need for this anymore, we're using CircleCI. Fixed with #8.
